name: Scheduled Build and Run

on:
  push:
    branches:
      - main
      - test
  schedule:
    - cron: "10 15 * * 1"  # 한국시간(KST) 월요일 00:10 (UTC 15:10)
  workflow_dispatch:  # ✅ 수동 실행 가능하게 추가

jobs:
  build-and-run:
    runs-on: ubuntu-latest  # 실행 환경 설정 (Ubuntu 최신 버전)

    steps:
      - name: Checkout Repository  # 저장소 코드 가져오기
        uses: actions/checkout@v3

      - name: Set up JDK 21  # ✅ Java 21 설정
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Create application.yml from Secrets  # ✅ GitHub Secrets에서 application.yml 생성
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      - name: Grant Execute Permission for Gradle  # Gradle 실행 권한 부여
        run: chmod +x gradlew

      - name: Build with Gradle  # Gradle 빌드 실행
        run: ./gradlew clean build --no-daemon

      - name: Run Java Application  # Java 애플리케이션 실행
        run: java -jar build/libs/*.jar